title: comexr
email: info@comexr.com
description: >- 
  Provides drivers and other packages for laptops sold by LaptopWithLinux.
baseurl: ""
url: "https://comexr.github.io"
github_username: comexr

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - tools/
  - doc/
